services:
  sonoplay-sm6:
    image: sonoplay-sm6:v1.2.1-sm6.latest
    build:
      context: /sonoplay # Change this to the path to your SonoPlay repository
      dockerfile: Dockerfile
    container_name: sonoplay
    restart: unless-stopped
    network_mode: host
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    env_file:
      - /sonoplay-config/.env # Change '/sonoplay-config' to your SonoPlay configuration path
    environment:
      TZ: Europe/Paris
      CONFIG_PATH: /config
    volumes:
      - /sonoplay-config/config:/config # Change '/sonoplay-config' to your SonoPlay configuration path